rm(list = ls())
library(tidyverse)
library(data.table)
library(readxl)
cat("\014") 
setwd("C:/Users/Diego/Documents/Rstudio_practice/Data_Science/chr3")
# dir.base<- file.path(
myData <- read.csv(file = 'Data1.csv')
myData1<- read.csv(file = 'Data2.csv')
h?ad(myData)
myData3<-rbind(myData,myData1)
myData33<-as.matrix(myData3$Expression)
mysum<-apply(myData33,2,sum)
# write.csv(myData3, file = "Data3.csv")
