rm(list = ls())
library(tidyverse)
library(data.table)
library(readxl)
cat("\014") 
setwd("C:/Users/awm2/Desktop/Academic and Old Files/Diego/R-Tutorial")
# dir.base<- file.path(
myData <- read.csv(file = 'Data1.csv')
myData1<- read.csv(file = 'Data2.csv')
head(myData)
myData3<-rbind(myData,myData1)
myData33<-as.matrix(myData3$Expression)
myIndex<-which.min(myData33)
write.csv(myData3, file = "Data3.csv")
